name: Update checkmarx scanner api
on:
  schedule:
    - cron:  '0 10 * * *'
jobs:
  updateCheckmarxJenkins:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Latest Checkmarx API version
        id: checkmarx-ast-scanner
        run: |
          echo ::set-output name=release_tag::$(curl -sL https://api.github.com/repos/CheckmarxDev/checkmarx-ast-scanner-plugin/releases/latest | jq -r ".tag_name")
          echo ::set-output name=current_tag::$(<checkmarx-ast-scanner.version)
      - name: Update Checkmarx scanner version
        if: steps.checkmarx-ast-scanner.outputs.current_tag != steps.checkmarx-ast-scanner.outputs.release_tag
        env:
          RELEASE_TAG: ${{ steps.checkmarx-ast-scanner.outputs.release_tag }}
        run: |
          # Update current release
          echo ${{ steps.checkmarx-ast-scanner.outputs.release_tag }} > checkmarx-ast-scanner.version
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update checkmarx-ast-scanner to ${{ steps.checkmarx-ast-scanner.outputs.release_tag }}
          title: Update Checkmarx-ast-scanner to ${{ steps.checkmarx-ast-scanner.outputs.release_tag }}
          body: |
            Updates [checkmarx-ast-scanner][1] to ${{ steps.checkmarx-ast-scanner.outputs.release_tag }}

            Auto-generated by [create-pull-request][2]

            [1]: https://github.com/CheckmarxDev/checkmarx-ast-scanner-plugin
            [2]: https://github.com/peter-evans/create-pull-request
          labels: dependencies, automated pr
          branch: checkmarx-ast-scanner-updates